# Generated by Django 6.0.6 on 2026-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("rack_id", models.IntegerField()),
                ("retail_price", models.FloatField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="routing_fue_latitud_6dc999_idx",
                    ),
                    models.Index(
                        fields=["state", "city"], name="routing_fue_state_217c0f_idx"
                    ),
                ],
            },
        ),
    ]
